// Datos para el globo "Did you know...?" (se pueden cambiar por los tuyos)
// Sin acentos: la fuente de 8 bits los dibuja ilegibles a este tamaño
const plain = (t) => t.normalize('NFD').replace(/[̀-ͯ]/g, '');

export const FACTS = [
  {
    en: 'THE FIRST COMPUTER "BUG" WAS A REAL MOTH TRAPPED IN A MACHINE IN 1947.',
    es: 'EL PRIMER "BUG" DE UNA COMPUTADORA FUE UNA POLILLA REAL ATRAPADA EN UNA MÁQUINA EN 1947.',
  },
  {
    en: 'THE FIRST MOUSE, FROM 1964, HAD A WOODEN SHELL.',
    es: 'EL PRIMER MOUSE, DE 1964, TENÍA UNA CARCASA DE MADERA.',
  },
  {
    en: 'THE WORD ROBOT COMES FROM THE CZECH "ROBOTA", MEANING FORCED LABOR.',
    es: 'LA PALABRA ROBOT VIENE DEL CHECO "ROBOTA", QUE SIGNIFICA TRABAJO FORZADO.',
  },
  {
    en: 'JAVASCRIPT WAS CREATED IN JUST 10 DAYS, IN 1995.',
    es: 'JAVASCRIPT SE CREÓ EN SOLO 10 DÍAS, EN 1995.',
  },
  {
    en: 'PIXEL STANDS FOR "PICTURE ELEMENT".',
    es: 'PIXEL ES LA UNIÓN DE "PICTURE ELEMENT": ELEMENTO DE IMAGEN.',
  },
  {
    en: 'THE FIRST .COM DOMAIN WAS REGISTERED IN 1985: SYMBOLICS.COM.',
    es: 'EL PRIMER DOMINIO .COM SE REGISTRÓ EN 1985: SYMBOLICS.COM.',
  },
  {
    en: 'PONG, ONE OF THE FIRST COMMERCIAL VIDEO GAMES, CAME OUT IN 1972.',
    es: 'PONG, UNO DE LOS PRIMEROS VIDEOJUEGOS COMERCIALES, SALIÓ EN 1972.',
  },
  {
    en: 'UNIMATE, THE FIRST INDUSTRIAL ROBOT, STARTED WORKING IN A FACTORY IN 1961.',
    es: 'UNIMATE, EL PRIMER ROBOT INDUSTRIAL, EMPEZÓ A TRABAJAR EN UNA FÁBRICA EN 1961.',
  },
  {
    en: 'EVERY LETTER ON MY SCREEN IS DRAWN WITH JUST 5x7 PIXELS.',
    es: 'CADA LETRA DE MI PANTALLA SE DIBUJA CON SOLO 5x7 PÍXELES.',
  },
  {
    en: 'THE FIRST WEBSITE EVER WAS PUBLISHED IN 1991 AND CAN STILL BE VISITED.',
    es: 'EL PRIMER SITIO WEB DE LA HISTORIA SE PUBLICÓ EN 1991 Y TODAVÍA SE PUEDE VISITAR.',
  },
].map((f) => ({ en: plain(f.en), es: plain(f.es) }));
