// Datos para el globo "¿Sabías que...?" (se pueden cambiar por los tuyos)
// Sin acentos: la fuente de 8 bits los dibuja ilegibles a este tamaño
const plain = (t) => t.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

export const FACTS = [
  'EL PRIMER "BUG" DE UNA COMPUTADORA FUE UNA POLILLA REAL ATRAPADA EN UNA MÁQUINA EN 1947.',
  'EL PRIMER MOUSE, DE 1964, TENÍA UNA CARCASA DE MADERA.',
  'LA PALABRA ROBOT VIENE DEL CHECO "ROBOTA", QUE SIGNIFICA TRABAJO FORZADO.',
  'JAVASCRIPT SE CREÓ EN SOLO 10 DÍAS, EN 1995.',
  'PIXEL ES LA UNIÓN DE "PICTURE ELEMENT": ELEMENTO DE IMAGEN.',
  'EL PRIMER DOMINIO .COM SE REGISTRÓ EN 1985: SYMBOLICS.COM.',
  'PONG, UNO DE LOS PRIMEROS VIDEOJUEGOS COMERCIALES, SALIÓ EN 1972.',
  'UNIMATE, EL PRIMER ROBOT INDUSTRIAL, EMPEZÓ A TRABAJAR EN UNA FÁBRICA EN 1961.',
  'CADA LETRA DE MI PANTALLA SE DIBUJA CON SOLO 5x7 PÍXELES.',
  'EL PRIMER SITIO WEB DE LA HISTORIA SE PUBLICÓ EN 1991 Y TODAVÍA SE PUEDE VISITAR.',
].map(plain);
